//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotiftClone
{
    using System;
    using System.Collections.Generic;
    
    public partial class albums
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public albums()
        {
            this.state = true;
            this.songs = new HashSet<songs>();
        }
    
        public int ID { get; set; }
        public int artistID { get; set; }
        public int typeID { get; set; }
        public int songCount { get; set; }
        public System.DateTime date { get; set; }
        public string name { get; set; }
        public bool state { get; set; }
    
        public virtual artists artists { get; set; }
        public virtual song_type song_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<songs> songs { get; set; }
    }
}
