//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotiftClone
{
    using System;
    using System.Collections.Generic;
    
    public partial class artists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public artists()
        {
            this.albums = new HashSet<albums>();
            this.artists_of_song = new HashSet<artists_of_song>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string stageName { get; set; }
        public int countryID { get; set; }
        public bool state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<albums> albums { get; set; }
        public virtual countries countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<artists_of_song> artists_of_song { get; set; }
    }
}
