
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SpotiftClone
{

using System;
    using System.Collections.Generic;
    
public partial class songs
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public songs()
    {

        this.state = true;

        this.artists_of_song = new HashSet<artists_of_song>();

        this.playedcount_countries = new HashSet<playedcount_countries>();

        this.user_playlist_songs = new HashSet<user_playlist_songs>();

    }


    public int ID { get; set; }

    public int albumID { get; set; }

    public int typeID { get; set; }

    public string name { get; set; }

    public System.DateTime date { get; set; }

    public int time { get; set; }

    public int playedCount { get; set; }

    public bool state { get; set; }



    public virtual albums albums { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<artists_of_song> artists_of_song { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<playedcount_countries> playedcount_countries { get; set; }

    public virtual song_type song_type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<user_playlist_songs> user_playlist_songs { get; set; }

}

}
