

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SpotiftClone
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class spotifydbEntities : DbContext
{
    public spotifydbEntities()
        : base("name=spotifydbEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<admins> admins { get; set; }

    public virtual DbSet<albums> albums { get; set; }

    public virtual DbSet<artists> artists { get; set; }

    public virtual DbSet<artists_of_song> artists_of_song { get; set; }

    public virtual DbSet<countries> countries { get; set; }

    public virtual DbSet<playedcount_countries> playedcount_countries { get; set; }

    public virtual DbSet<playlists> playlists { get; set; }

    public virtual DbSet<song_type> song_type { get; set; }

    public virtual DbSet<songs> songs { get; set; }

    public virtual DbSet<subscriber_type> subscriber_type { get; set; }

    public virtual DbSet<user_follows> user_follows { get; set; }

    public virtual DbSet<user_playlist_songs> user_playlist_songs { get; set; }

    public virtual DbSet<users> users { get; set; }

}

}

