
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SpotiftClone
{

using System;
    using System.Collections.Generic;
    
public partial class user_playlist_songs
{

    public int ID { get; set; }

    public int playlistID { get; set; }

    public int songID { get; set; }



    public virtual playlists playlists { get; set; }

    public virtual songs songs { get; set; }

}

}
