
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SpotiftClone
{

using System;
    using System.Collections.Generic;
    
public partial class users
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public users()
    {

        this.admins = new HashSet<admins>();

        this.playlists = new HashSet<playlists>();

        this.user_follows = new HashSet<user_follows>();

        this.user_follows1 = new HashSet<user_follows>();

    }


    public int ID { get; set; }

    public string name { get; set; }

    public string surname { get; set; }

    public string mail { get; set; }

    public string password { get; set; }

    public int subscriberID { get; set; }

    public int countryID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<admins> admins { get; set; }

    public virtual countries countries { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<playlists> playlists { get; set; }

    public virtual subscriber_type subscriber_type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<user_follows> user_follows { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<user_follows> user_follows1 { get; set; }

}

}
