//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotiftClone
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_follows
    {
        public int ID { get; set; }
        public int userID { get; set; }
        public int followingID { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
